version: 2.1 # CircleCI syntax version
jobs: # a collection of steps
  build: # runs that are not using Workflows must have a `build` job as the entry point
    docker:
      - image: circleci/node:10.16.3 # the first image is the primary container; this is where all `steps` will run
    steps: # a collection of executable commands 
      - checkout # check out source code to working directory
      - restore_cache: 
          name: Restore Dependency Cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: NPM Install
          command: npm install
      - save_cache:
          name: Save Dependency Cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run: #code climate test reporter
          name: Install Test Reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
     
      - run: #eslint
          name: eslint
          command: npm run lint
          
      - run: # run tests
          name: Run Tests and Coverage
          environment: 
            CC_TEST_REPORTER_ID: 3f28740af30153569a3c81da5948b1c12aa13760212b2f2cf59cc8c585e78871
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ];
            then
              ./cc-test-reporter before-build
            fi
            npm run coverage
            if [ "$CIRCLE_BRANCH" == "master" ];
            then
              ./cc-test-reporter after-build -p "/home/circleci/project/" -t lcov --debug --exit-code $?
            fi
      - store_artifacts:
          path: coverage/lcov-report
          destination: coverage
